### ISSUE TITLE
Wrong `type` value in CIPM Meetings

### ISSUE THREAD

**Issue by manuel489** [metanorma/bipm-data-outcomes#11]
In CIPM, there are several cases where `type=recommendation` should be `type=resolution`.

Check [Meeting 41](https://github.com/metanorma/bipm-data-outcomes/blob/main/cipm/meetings-en/meeting-41.yml#L12-L15), as an example of several ones.
(Look at the provided URL in the yaml file to confirm the correct type.)

This is generating fetching issues from relaton-bipm.

**Comment by ronaldtse** [comment]
BTW @manuel489 it is the title that determines the type, not the URL. The URL are all "resolution" but the pages title can give "Recommendation".

**Comment by manuel489** [comment]
Types were corrected manually and pushed to main.
Closing.

**Comment by ronaldtse** [comment]
Re-opening this for @webdev778 .
