### ISSUE TITLE
Run GHA to allow bipm-data-importer to import data daily

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-data-outcomes#13]
The BIPM often updates it’s website to provide additional resolutions and decisions. 

Upon our request, they just added the following data:

CIPM Meeting (1950)
CIPM: Proceedings of the 43rd meeting (1950): https://www.bipm.org/documents/20126/56719035/CIPM43.pdf/172ac044-091b-4162-f9b4-f2b095d0b173.

CIPM Meeting (1962)
CIPM: Proceedings of the 51st meeting (1962): https://www.bipm.org/documents/20126/56719035/CIPM51.pdf/deb1a820-e301-a5af-1630-f970118d972c.

CIPM Meeting 4 (1879)
CIPM: Proceedings of the 4th meeting (1879): https://www.bipm.org/documents/20126/56719035/CIPM4.pdf/47e647d4-26c2-d3d6-b367-e749fb22b261.

We need to have a GHA workflow that checks for new data and imports this information daily.

**Comment by ronaldtse** [comment]
@webdev778 can you get this done today? Thanks.

**Comment by webdev778** [comment]
Fixed by #24
