### ISSUE TITLE
Run bipm-data-importer to import CIPM meetings 4, 43 and 51

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-data-outcomes#14]
The meetings have been entered by the BIPM:
https://www.bipm.org/en/committees/ci/cipm/meetings

Specifically, 

* https://www.bipm.org/en/committees/ci/cipm/4-1879
* https://www.bipm.org/en/committees/ci/cipm/43-1950
* https://www.bipm.org/en/committees/ci/cipm/51-1962

The corresponding French versions also exist.

This was originally intended to be done via #13 but we have to do it ASAP to complete the SI Brochure work.

Once this is done, @andrew2net please help update relaton-data-bipm. Thanks!

**Comment by webdev778** [comment]
Related to #15: The previous behavior was to not include meetings that don't include resolutions. This will be amended with the next commit.

**Comment by webdev778** [comment]
This is fixed now. Feel free to close if confirmed.

**Comment by ronaldtse** [comment]
Thank you @webdev778 , I can confirm that the issues are fixed.
