### ISSUE TITLE
Missed FR version

### ISSUE THREAD

**Issue by andrew2net** [metanorma/bipm-data-outcomes#15]
There is EN file https://github.com/metanorma/bipm-data-outcomes/blob/main/cipm/meetings-en/meeting-4.yml but there in't FR version in https://github.com/metanorma/bipm-data-outcomes/tree/main/cipm/meetings-fr/

**Comment by webdev778** [comment]
Do note, that:
- English version has a resolution: https://www.bipm.org/en/committees/ci/cipm/4-1879
- French version has not: https://www.bipm.org/fr/committees/ci/cipm/4-1879

I will follow up this with a commit that includes empty meetings which will fix this issue.

**Comment by webdev778** [comment]
This is fixed now. Feel free to close if confirmed.
