### ISSUE TITLE
Duplicated Resolutions across a "split meeting"

### ISSUE THREAD

**Issue by andrew2net** [metanorma/bipm-data-outcomes#17]
The part 1 of the document https://github.com/metanorma/bipm-data-outcomes/blob/main/cipm/meetings-en/meeting-104-1.yml has decisions with identifiers 104-1, 104-2, ..., 104-26. Example: https://github.com/metanorma/bipm-data-outcomes/blob/b2f5352356802001ff91b531000e8eff8979f109/cipm/meetings-en/meeting-104-1.yml#L135
The part 2 https://github.com/metanorma/bipm-data-outcomes/blob/main/cipm/meetings-en/meeting-104-2.yml has decisions with 104-27, 104-28, ..., 104-48. Example: https://github.com/metanorma/bipm-data-outcomes/blob/b2f5352356802001ff91b531000e8eff8979f109/cipm/meetings-en/meeting-104-2.yml#L135
Since the numeration was unique across the parts we created decisions with document identifiers `Decision 104-01`, `Decision 104-02`, ..., `Decision 104-48`.

Now we have recommendations with identifiers 1 and 2 in the first part. Example: https://github.com/metanorma/bipm-data-outcomes/blob/b2f5352356802001ff91b531000e8eff8979f109/cipm/meetings-en/meeting-104-1.yml#L18
And same identifiers in the second. Example: https://github.com/metanorma/bipm-data-outcomes/blob/b2f5352356802001ff91b531000e8eff8979f109/cipm/meetings-en/meeting-104-2.yml#L18
The question is: should we add part to document identifiers? Like `Recommendation 104-1-01`, `Recommendation 104-1-02` `Decision 104-1-1`, ...`Decision 104-1-26`, `Recommendation 104-2-01`, `Recommendation 104-2-02`, `Decision 104-2-27`, ...
Or should we update this repository to have unique identifiers across the parts?

**Comment by ronaldtse** [comment]
@andrew2net I noticed that these two recommendations are identical:

https://github.com/metanorma/bipm-data-outcomes/blob/b2f5352356802001ff91b531000e8eff8979f109/cipm/meetings-en/meeting-104-1.yml#L18

https://github.com/metanorma/bipm-data-outcomes/blob/b2f5352356802001ff91b531000e8eff8979f109/cipm/meetings-en/meeting-104-2.yml#L18

From the source pages, I can see that CIPM Meeting 104 Sessions 1 and 2 both show the same Recommendation 1 and Recommendation 2:
* https://www.bipm.org/en/committees/ci/cipm/104-_1-2015
* https://www.bipm.org/en/committees/ci/cipm/104-_2-2015

> The question is: should we add part to document identifiers? 

No. Meeting parts are to be treated as a single meeting, so Decisions, Recommendations etc should be uniquely numbered.

@webdev778 could you help improve bipm-data-importer to handle the potential duplicated information across meeting parts? Thanks!

**Comment by webdev778** [comment]
I have verified it and it only happens for those two cases. In a couple of minutes I'm submitting a PR to correct that.

**Comment by webdev778** [comment]
There were other problems with duplicate IDs, I solved all. The commits in this issue will reference related problems, they need to be fixed upstream.

**Comment by ronaldtse** [comment]
Thank you @webdev778 , I will report them back to BIPM.
