### ISSUE TITLE
CCTF French meeting page mistakenly pointing to English version

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-data-outcomes#19]
https://github.com/metanorma/bipm-data-outcomes/blob/55bba1f2de0e4fce665dcd3cfc341db5ca879f38/cctf/meetings-fr/meeting-5.yml#L7

Should be pointing to:
* https://www.bipm.org/fr/committees/cc/cctf/5-1970

This needs to be fixed in bipm-data-importer.

**Comment by andrew2net** [comment]
fixed https://github.com/metanorma/bipm-data-outcomes/blob/a9c1260d318c13fd94607a6ffedad6316824a6f3/cctf/meetings-fr/meeting-5.yml#L7

**Comment by ronaldtse** [comment]
@webdev778 can you help check that this doesn’t happen with the new code? Thanks.

**Comment by webdev778** [comment]
Fixed
