### ISSUE TITLE
Use bipm-data-importer released gem directly

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-data-outcomes#25]
We should use the released bipm-data-importer gem instead of from the main Git branch.

This code should just be `gem install bipm-data-importer` and then execute its commands.

_Originally posted by @ronaldtse in https://github.com/metanorma/bipm-data-outcomes/pull/24#discussion_r1063056934_

**Comment by ronaldtse** [comment]
bipm-data-importer v0.1.2 has been released.

**Comment by webdev778** [comment]
Fixed
