### ISSUE TITLE
Missing French CCT meeting 30

### ISSUE THREAD

**Issue by andrew2net** [metanorma/bipm-data-outcomes#27]
There is an English version of CCT meeting 30 `cct/meetings-en/meeting-30.yml`, but there is no same file in French `cct/meetings-fr/meeting-30.yml`.

**Comment by ronaldtse** [comment]
This file now exists:
* https://github.com/metanorma/bipm-data-outcomes/blob/main/cct/meetings-fr/meeting-30.yml

Closing.
