### ISSUE TITLE
Declaration type instead statement.

### ISSUE THREAD

**Issue by andrew2net** [metanorma/bipm-data-outcomes#30]
As per [Guide to referencing BIPM information resources](https://github.com/metanorma/bipm-editor-guides/blob/main/sources/bipm-outcomes-en.adoc#publication-identifier-1) we should use "Statement" type in English notation. In the bipm-data-outcomes we have "declaration" instead "statement". For example [CGPM DECL (1971)](https://github.com/metanorma/bipm-data-outcomes/blob/7bc162398894a2d9dff556e605ca9cf522586bec/cgpm/meetings-en/meeting-14.yml#L236).

**Comment by ronaldtse** [comment]
This is fixed, e.g. https://github.com/metanorma/bipm-data-outcomes/blob/c5ee63e5f570666ff19bf8f19ca996999723c54e/cgpm/meetings-en/meeting-03.yml#L13

Now it uses `statement` as type.
