### ISSUE TITLE
Use bot to refresh repository daily using Pull Requests so we don't override good data

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-data-outcomes#31]
The fetches stopped! We need to ensure that this is run daily.

Let's also take this chance to upgrade the workflows here.

@CAMOBAP just like how it's done at metanorma on the XSLT update scripts.

**Comment by ronaldtse** [comment]
@CAMOBAP how come the daily job has been stopped now? We need to resume this ASAP. Thanks.

**Comment by CAMOBAP** [comment]
@ronaldtse yep, i missed the part with PR, should we update existing PR if there i a one in progress?

**Comment by ronaldtse** [comment]
What do you think? Is that better?

**Comment by CAMOBAP** [comment]
I think maintain/update a single PR will be better, but it may depends on the reviewers preferences

**Comment by CAMOBAP** [comment]
@ronaldtse works now https://github.com/metanorma/bipm-data-outcomes/pull/34 who should I keep as reviewers?

**Comment by ronaldtse** [comment]
Can you alert @andrew2net @opoudjis and @ronaldtse (myself)? Thanks!
