### ISSUE TITLE
Add missing resolutions

### ISSUE THREAD

**Issue by anermina** [metanorma/bipm-data-outcomes#32]
In the following files, the `resolutions` field is empty.
https://github.com/metanorma/bipm-data-outcomes/blob/main/cipm/meetings-fr/meeting-4.yml
https://github.com/metanorma/bipm-data-outcomes/blob/main/jcrb/meetings-fr/meeting-44.yml
https://github.com/metanorma/bipm-data-outcomes/blob/main/jcrb/meetings-fr/meeting-45.yml
https://github.com/metanorma/bipm-data-outcomes/blob/main/jcrb/meetings-fr/meeting-46.yml

This issue causes the English hyperlink to CIPM RES (1879) to appear in the French version of the BIPM SI Brochure, which is reported in https://github.com/metanorma/bipm-si-brochure/issues/228, and currently represents a blocking point for publishing the Brochure.

**Comment by ronaldtse** [comment]
This ticket will be fixed once this is fixed:
* https://github.com/metanorma/bipm-data-importer/issues/49

**Comment by andrew2net** [comment]
@ronaldtse the ticket https://github.com/metanorma/bipm-data-importer/issues/49 is fixed, but there is a new issue now https://github.com/metanorma/bipm-data-outcomes/issues/33

**Comment by ronaldtse** [comment]
Fixed. Closing.
